package com.ultimatesoftware.banking.account.common;

public enum AccountEventType {
    CREATED,
    CREDITED,
    DEBITED,
    DELETED,
    RELEASED,
    UPDATED,
    DESTINATION_AQUIRED,
    TRANSACTION_FAILED,
    TRANSFER_CANCELLED,
    SOURCE_AQUIRED,
    TRANSFER_CONCLUDED,
    TRANSFER_FAILED_TO_START,
    TRANSFER_STARTED,
    TRANSACTION, TRANSFER_WITHDRAW_CONCLUDED
}
